# Generated by Django 4.1.3 on 2022-12-12 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('apelido', models.CharField(max_length=50, verbose_name='Apelido')),
                ('custo_hora', models.FloatField(max_length=12, verbose_name='Custo/Hora')),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('tempo_producao', models.IntegerField(verbose_name='Tempo Produção')),
                ('tempo_ajuste', models.IntegerField(verbose_name='Tempo Ajuste')),
            ],
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('cod_local', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código Local')),
                ('cod_estrangeiro', models.CharField(max_length=50, verbose_name='Código Estrangeiro')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, verbose_name='Código')),
                ('data_entrega', models.DateField(verbose_name='Data de Entrega')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Qtd.')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.peca', verbose_name='ID-Peça')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pedido', verbose_name='ID-Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.maquina', verbose_name='ID-Máquina')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.operacao', verbose_name='ID-Operação')),
            ],
        ),
        migrations.AddField(
            model_name='operacao',
            name='peca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.peca', verbose_name='ID-Peça'),
        ),
    ]
