# Generated by Django 4.1.3 on 2022-12-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
            preserve_default=False,
        ),
    ]
