# Generated by Django 4.1.3 on 2022-12-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pedido_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidopeca',
            name='quantidade_feita',
            field=models.IntegerField(default=0, verbose_name='Qtd. Feita'),
            preserve_default=False,
        ),
    ]
