# Generated by Django 4.1.3 on 2022-12-20 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pedidopeca_quantidade_feita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidopeca',
            name='quantidade_feita',
        ),
        migrations.CreateModel(
            name='FilaOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Qtd.')),
                ('quantidade_feita', models.IntegerField(verbose_name='Qtd. Feita')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.maquina', verbose_name='ID-Maquina')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.operacao', verbose_name='ID-Operação')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pedido', verbose_name='ID-Pedido')),
            ],
        ),
    ]
